version: "3"

services:
  frontend:
    image: estebanbaron/frontend-security-project
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    image: estebanbaron/backend-security-project
    build:
      context: ./backend
    ports:
      - "3000:3000"
