version: "3"

services:
  frontend:
    image: estebanbaron/frontend-security-project
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    image: estebanbaron/backend-security-project
    build:
      context: ./backend
    ports:
      - "3000:3000"
