apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-pod-limits
spec:
  background: false
  rules:
    - name: add-pod-limits
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchesJson6902: |-
          - path: "/spec/containers/0/resources"
            op: add
            value:
              limits:
                memory: "500Mi"
                cpu: "1000m"
